### PR TITLE
Add some test functions to ppigrf

### PR DESCRIPTION
**Pull request by santisoler**
Add tests against precomputed IGRF values. There are small differences between the results that `ppigrf` generates and the ones that the NCEI Calculator produces on dates that require some interpolation along the dates. The difference is not significant.

### CODE REVIEW

**Comment by santisoler** [comment]
@klaundal I've wrote some tests that compare `ppigrf` results against a precomputed grid I got from the [NCEI Calculator](https://www.ngdc.noaa.gov/geomag/calculators/magcalc.shtml?useFullSite=true). I'm seeing some discrepancies between them. Do you have any idea why it might be happening? It's due to floating point precision? Maybe a different set of coefficients? Would love to hear your opinion on this.

**Comment by klaundal** [comment]
@santisoler I did a quick comparison for one point with the NOAA calculator now. The deviations are very small, but too large to be floating point precision I think. I doubt that the coefficient files are different. One possibility is that it is an issue with how the time interpolation between model coefficients is implemented. And/or the conversion between geodetic and geocentric coordinates and components (I get a very good match in the eastward component, which is not affected by this). 

Still, the deviations are tiny, typically less than 1 nT. This rarely has any practical consequence, but it would be good to know why it happens. Comparison with an open code would be preferable though.

**Comment by santisoler** [comment]
I suspect you're right and this is coming from the interpolations on the dates. I also checked `ppigrf` against outputs of [`igrf`](https://github.com/space-physics/igrf) (which I suspect the NCEI calculator is running on the background) and I get the same differences. I couldn't generate a grid with `igrf` because their code was failing due to some Xarray error (probably they were using a different version of Xarray). But I checked with some individual points and the differences are still there.

I've just run a quick check comparing on 2020-01-01 (so no interpolation should be carried out) and the tests pass. So apparently the difference is coming from the date interpolation. I will push new tests with no interpolation on date.

**Comment by santisoler** [comment]
Hi @klaundal! After a few weeks (time flies!) I managed to fix the tests so they pass. I've increased the `atol` in the second case (in which we have to interpolate along the dates). I think this is sufficient for now and it should be ready to be merged. Let me know what you think!

**Pull request merged**
